### ISSUE TITLE
vaadin-bar-chart expands on update

### ISSUE THREAD

**Issue by grimly** [vaadin/vaadin-charts#108]
This issue was first found and [reported](https://github.com/vaadin/expense-manager-demo/issues/18) on the [Expense Manager Demo](https://github.com/vaadin/expense-manager-demo).

As I discovered in the element inspector, the issue comes from the vaadin-bar-chart element.
This could not be the only element affected by this issue.

> Tested against Firefox 39.0 on a wide screen.
> 
> The chart on the right side of the screen gets bigger and bigger whenever the window (viewport) is resized or it refresh itself with new data.

**Comment by johannesh2** [comment]
Similar issue was fixed in Charts 6.0 alpha6. Closing this old issue.
