### ISSUE TITLE
AbstractSeries.setVisible() not synchronized with client

### ISSUE THREAD

**Issue by jan-richter-saxess** [vaadin/vaadin-charts#147]
The plot visibility is not written back to the server.

Hiding a plot by AbstractSeries.setVisible(false) and unhiding a plot by clicking its legend name, AbstractSeries.isVisible() returns false - it should return true now. Refreshing the page via F5 will hide the plot again.

**Comment by alvarezguille** [comment]
This repo is for the WebComponent version of vaadin charts, issues for Java version should be created in [github.com/vaadin/charts](https://github.com/vaadin/charts/issues/new).
Please create a new issue in charts project, sorry for the inconvenience but can't move issues in github.
Thanks
