### ISSUE TITLE
vaadin-charts 5.0.0 not in maven central

### ISSUE THREAD

**Issue by stadler** [vaadin/vaadin-charts#184]
Hi

The new version of vaadin-charts does not seem to be deployed to maven central.
By when do you plan to do so?

Regards

**Comment by johannesh2** [comment]
Hello. The vaadin-charts is the Web Component version of Charts and added only support for Polymer 2 and no new features. The Charts element is available through Bower. The latest Java version is still 4.0.0 for Vaadin 8 and is available through Maven.
