### ISSUE TITLE
Some chart types are unusable due to missing imports (6.0-preview)

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-charts#198]
I tried to use a solidgauge chart type, but that failed because highcharts solid-gauge.js is not imported and there is no clear way to add it yourself.

I suspect funnel at least is similar as it also has an own js file.

**Comment by DiegoCardoso** [comment]
True that. I guess we should keep the list of Highcharts modules as in v5.0.0.

**Comment by DiegoCardoso** [comment]
I have added the missing files in order to support the same charts that we have at Vaadin Charts 5. If you are trying to make it work through JSON API, make sure to add `true` as the second parameter of the `update()` method call.
