### ISSUE TITLE
Could not theme chart in preview-6.0

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-charts#200]
6.0 uses the STYLED mode, where you give css to theme charts. However, web component boundary makes it hard to give CSS to apply to the chart. I was not able to change any colors.

**Comment by johannesh2** [comment]
Merged to 6.0-preview https://github.com/vaadin/vaadin-charts/pull/206. You can now put e.g.

```
<dom-module id="vaadin-charts-custom-theme" theme-for="vaadin-chart">
    <template>
        <style include="vaadin-charts-default-theme">
            .highcharts-column-series rect.highcharts-point {
                stroke: rgb(255, 0, 0);
            }
        </style>
    </template>
</dom-module>
```
