### ISSUE TITLE
Setting a fixed height on <vaadin-chart> does not size the highcharts container propertly

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-charts#245]
Version: charts 6 preview

Setting the height of a <vaadin-chart> to a set pixel height should constrain the chart to that height.

**Comment by Peppe** [comment]
I have a workaround for this in place, basically setting the height of the `<div id="chart">` within the shadow root gets you the correct height chart. 

HTML:
```HTML
<vaadin-chart id="my-chart"></vaadin-chart>
```

CSS:
```CSS
:host(#my-chart) #chart {
  height: 150px;
}
```

A proper fix is of course needed but this works with current preview versions.
