### ISSUE TITLE
Take the default vaadin-chart-series type from vaadin-chart

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-charts#292]
<vaadin-charts> version 6.1-alpha1.

I have a areaspline chart, configured with additional-options chart.type: areaspline. If I now add series to it with name and data, i get areaspline seriers in it. If I however use the child element 
```html
<vaadin-chart-series values="[1037451, 918249, 984372, 983721, 948372, 1192301]">
</vaadin-chart-series>
```
then I get line series and not areaspline series. This is because default type for <vaadin-chart-series> is line. 

Make it use the type that the chart defines as default.

**Comment by johannesh2** [comment]
I agree. Default value for vaadin-chart-series is a good one, but shouldn't override the one defined in vaadin-chart.

**Comment by DiegoCardoso** [comment]
This PR should fix this issue: https://github.com/vaadin/vaadin-charts/pull/288

**Comment by DiegoCardoso** [comment]
Property `type` doesn't have a default value anymore, so it won't override the default type coming from the chart.
