### ISSUE TITLE
Update 6.1 master to HighCharts 6

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-charts#367]

**Comment by oluwasayo** [comment]
https://github.com/highcharts/highcharts/issues/8417

**Comment by johannesh2** [comment]
Duly noted, but I don't think it's a blocker. If you can apply that workaround somehow even better.

**Comment by oluwasayo** [comment]
Pay attention to stacking regression in Highcharts 6.
https://github.com/highcharts/highcharts/issues/8475
