### ISSUE TITLE
Create HTML API version vaadin-charts-flow demos

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-charts#373]
* Create a separate demo app and deploy to charts.demo.vaadin.com/vaadin-charts
* IE11 needs to work too

**Comment by Haprog** [comment]
Btw the vaadin-charts-flow demos only show 14 chart types (out of the 24 listen at vaadin.com). So there is no Flow demo for 10 of the chart types atm. And we don't even list all the supported chart types (there are more than 24).

Optimal case would be to have a separate demo of each chart type so they could be individually embedded directly on vaadin.com. That might require a bit more planning though.

**Comment by marcushellberg** [comment]
We should build the new demos so that we can embed them on our site like we do for all the other components. I realize it'll be more work, but the website UX will be much better.

**Comment by johannesh2** [comment]
Rewriting our demo app is not the top-most priority currently. We will most likely do it later in #380.
