### ISSUE TITLE
Area Range chart series are not visible until forced update (v6.1.0-beta1)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-charts#395]
As a developer I expect to see an area range chart series to show up on the chart as any other series. At the moment there is an issue with this series type:

```html
<vaadin-chart type="arearange"
    title="Temperature variation by day"
    additional-options='{"xAxis": {"type": "datetime"}}'>
  <vaadin-chart-series id="series" values="[[data]]"></vaadin-chart-series>
</vaadin-chart>
```

The snippet above requires a forced update of the series before it becomes visible:
`this.$.series._series.update({data: this.$.series.values})`

See a live demo at https://vaadin-charts-arearange-61.glitch.me/ (source at https://glitch.com/edit/#!/vaadin-charts-arearange-61)

**Comment by DiegoCardoso** [comment]
Just to add that this seems to be due to `ChartLabelsMapper#map` which is leaving some values out of the data.
