### ISSUE TITLE
Vaadin Flow : Chart Data Series Unique Color

### ISSUE THREAD

**Issue by DabhiGhanshyam** [vaadin/vaadin-charts#417]
Hello Team,

I have one column chart. Its repeating series color after some columns. I have set option **_setColorByPoint = true_** but still chart repeats color.

How to give unique color to each data series?

Please refers to attached file.
![chartrepeatcolors](https://user-images.githubusercontent.com/30623161/45160529-524b9380-b207-11e8-9292-003129b0c599.png)

I have also posted same question here:
_https://vaadin.com/forum/thread/17256776/vaadin-flow-chart-data-series-unique-color_

Please help. Thanks

**Comment by rolfsmeds** [comment]
See charts styling documentation here: https://vaadin.com/docs/v14/charts/java-api/css-styling.html

Charts 9.0 also reintroduced a java styling API (currently V18 only, see https://vaadin.com/docs/v18/charts/java-api/css-styling.html)
