### ISSUE TITLE
PlotLine labels do not work in browsers that support Array.prototype.flat()

### ISSUE THREAD

**Issue by anselm92** [vaadin/vaadin-charts#420]
Since the latest chrome and firefox update, plotlinelabels won't show in gauge charts.
See related issue in highcharts: https://github.com/highcharts/highcharts/issues/8477
Please update highcharts to version 6.1.3 as soon as possible, since this is a very critical thing.

**Comment by alvarezguille** [comment]
Fixed in [v6.2.0-alpha2](https://github.com/vaadin/vaadin-charts/releases/tag/v6.2.0-alpha2)
