### ISSUE TITLE
Accessibility features can't be disabled.

### ISSUE THREAD

**Issue by edler-san** [vaadin/vaadin-charts#435]
Trying to disable the accessibility feature to get rid of the tooltip ('Monthly Average Rainfall' in screenshot) is not possible. 

This is due to issues in Highcharts (https://github.com/highcharts/highcharts/issues/6491, https://github.com/highcharts/highcharts/issues/9894).

![image](https://user-images.githubusercontent.com/19165931/53029909-2006b900-346a-11e9-8ce6-4b323c262089.png)

**Comment by edler-san** [comment]
Moved to vaadin-charts-flow.

**Comment by oysteinmoseng** [comment]
Just a comment from Highcharts: This tooltip is being disabled per default from our next version.

**Comment by alvarezguille** [comment]
Thanks for the info @oysteinmoseng, is that change coming with the 7.1 Accessibility Improvements? We are still using 6.1.4 for now.

**Comment by oysteinmoseng** [comment]
@alvarezguille That is correct. 7.1 is expected to be released in Q2 this year.
