### ISSUE TITLE
align project structure with other flow components

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-charts#498]
This should be the structure:
vaadin-charts-flow
vaadin-charts-flow-testbench
vaadin-charts-flow-demo
vaadin-charts-flow-integration-tests

It needs to be performed in the mono-repo project, but it should be nice that the original project also follows the convention

**Comment by web-padawan** [comment]
Done in the monorepo: https://github.com/vaadin/vaadin-flow-components/tree/master/vaadin-charts-flow-parent
