### ISSUE TITLE
Exporting chart as bytes array of PNG, JPEG, SVG, and PDF

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/vaadin-charts#524]
It would be a good feature to be able to export the chart as bytes array of PNG, JPEG, SVG, or PDF on server side in order to have it merged with other data to create a single PDF or Excel or whatever file needed.

**Comment by rolfsmeds** [comment]
Closing this in favor of https://github.com/vaadin/vaadin-charts/issues/508 (as there are no plans to integrate converstion to other formats than SVG, as that is better left to dedicated libraries)
