### ISSUE TITLE
Vaadin Flow : Chart Data Series Unique Color

### ISSUE THREAD

**Issue by DabhiGhanshyam** [vaadin/vaadin-charts#528]
I have one column chart. Its repeating series color after some columns. I have set property **_setColorByPoint = true_** but still chart repeats color.

How to give **unique color to each data series**?

Please refers to below screen-shot.
![chartrepeatcolors](https://user-images.githubusercontent.com/30623161/45354156-a923e500-b5da-11e8-9e6b-c06d0eb913f7.png)

Please help. Thanks

**Comment by rolfsmeds** [comment]
Closing as duplicate of https://github.com/vaadin/vaadin-charts/issues/417
