### ISSUE TITLE
FastClasspathScanner is outdated -- consider porting to ClassGraph

### ISSUE THREAD

**Issue by classgraph-robot** [vaadin/vaadin-charts#530]
Your project, `vaadin/vaadin-charts-flow`, depends on the outdated library FastClasspathScanner in the following source files:

* [`demo/src/main/java/com/vaadin/flow/component/charts/MainView.java`](https://github.com/vaadin/vaadin-charts-flow/tree/master/demo/src/main/java/com/vaadin/flow/component/charts/MainView.java)

FastClasspathScanner has been significantly reworked since the version your code depends upon:

* a significant number of bugs have been fixed
* some nontrivial API changes have been made to simplify and unify the API
* FastClasspathScanner has been renamed to ClassGraph: https://github.com/classgraph/classgraph

ClassGraph is a significantly more robust library than FastClasspathScanner, and is more future-proof. All future development work will be focused on ClassGraph, and FastClasspathScanner will see no future development.

Please consider porting your code over to the new ClassGraph API, particularly if your project is in production or has downstream dependencies:

* https://github.com/classgraph/classgraph/wiki/Porting-FastClasspathScanner-code-to-ClassGraph
* https://github.com/classgraph/classgraph/wiki/Code-examples
* https://github.com/classgraph/classgraph/wiki/ClassGraph-API

Feel free to close this bug report if this code is no longer in use. (You were sent this bug report because your project depends upon FastClasspathScanner, and has been starred by 4 users. Apologies if this bug report is not helpful.)

**Comment by web-padawan** [comment]
The relevant file was removed by https://github.com/vaadin/vaadin-charts-flow/pull/315. Closing.
