### ISSUE TITLE
Automatically generated color in chart is different from corresponding color in chart legend (Vaadin 17)

### ISSUE THREAD

**Issue by NicolasErnst** [vaadin/vaadin-charts#553]
I have created a pie chart following the online example at https://demo.vaadin.com/charts/PieWithLegend. 

Unfortunately the color of the second legend entry does not match the corresponding color in the pie chart.  All other entries seem to match the colors in the pie charts. 

This can be easily reproduced by using the example from the link under Vaadin 17 and it seems to affect various / all diagram types.

![image](https://user-images.githubusercontent.com/28729414/95839980-e91e9e80-0d43-11eb-97b4-55719e455d38.png)

**Comment by yuriy-fix** [comment]
Dear @NicolasErnst , 
Could you please provide a code snippet to reproduce the issue.
Are you using java API to set colors?
Do you have a custom theme? Are you including the default theme or customizing the custom css properties for colors?

**Comment by NicolasErnst** [comment]
Hello @yuriy-fix, 
I use the Java API to create the diagrams. However, I do not set colors, neither via the API nor via CSS properties. I use the colors generated by Vaadin Charts. 
I also do not use a custom theme. 

Here is the requested code snippet to reproduce: 

``` 
public void drawMinimalExample() {
	Chart pieChart = new Chart(ChartType.PIE); 
		
	PlotOptionsPie plotOptions = new PlotOptionsPie(); 
	plotOptions.setShowInLegend(true);
		
	DataSeries data = new DataSeries(); 
	data.add(new DataSeriesItem("One", 1));
	data.add(new DataSeriesItem("Two", 2));
	data.add(new DataSeriesItem("Three", 3));
		
	Configuration conf = pieChart.getConfiguration();
	conf.setTitle("Minimal example");
	conf.setPlotOptions(plotOptions);
	conf.setSeries(data);
		
	add(pieChart);
}
``` 

This snippet leads to the following diagram: 
<img width="204" alt="3Elements" src="https://user-images.githubusercontent.com/28729414/96731356-76529a80-13b7-11eb-9cc2-5285c1633b21.PNG">

When you add more DataSeriesItems, you can see that the colors of element two and four are reversed: 

```
 public void drawMinimalExample() {
	Chart pieChart = new Chart(ChartType.PIE); 
		
	PlotOptionsPie plotOptions = new PlotOptionsPie(); 
	plotOptions.setShowInLegend(true);
		
	DataSeries data = new DataSeries(); 
	data.add(new DataSeriesItem("One", 1));
	data.add(new DataSeriesItem("Two", 2));
	DataSeriesItem pinkItem = new DataSeriesItem("Three", 3); 
	pinkItem.setColor(SolidColor.PINK);
	data.add(pinkItem);
		
	Configuration conf = pieChart.getConfiguration();
	conf.setTitle("Minimal example");
	conf.setPlotOptions(plotOptions);
	conf.setSeries(data);
		
	add(pieChart);
}
```

<img width="208" alt="ColoredDataSeriesItem" src="https://user-images.githubusercontent.com/28729414/96731522-a39f4880-13b7-11eb-8c13-f532379e3c4b.PNG">

**Comment by NicolasErnst** [comment]
By the way, I do not know if the following is desired behaviour: 

``` 
public void drawMinimalExample() {
	Chart pieChart = new Chart(ChartType.PIE); 
		
	PlotOptionsPie plotOptions = new PlotOptionsPie(); 
	plotOptions.setShowInLegend(true);
		
	DataSeries data = new DataSeries(); 
	data.add(new DataSeriesItem("One", 1));
	data.add(new DataSeriesItem("Two", 2));
	DataSeriesItem pinkItem = new DataSeriesItem("Three", 3); 
	pinkItem.setColor(SolidColor.PINK);
	data.add(pinkItem);
		
	Configuration conf = pieChart.getConfiguration();
	conf.setTitle("Minimal example");
	conf.setPlotOptions(plotOptions);
	conf.setSeries(data);
		
	add(pieChart);
}
``` 

Here I tried to color the third element pink. But as you can see in the following picture, the color is only changed in the legend but not in the diagram.

<img width="208" alt="ColoredDataSeriesItem" src="https://user-images.githubusercontent.com/28729414/96732968-37bddf80-13b9-11eb-9b00-4fb898a81fdf.PNG">

**Comment by alvarezguille** [comment]
Hi @NicolasErnst 

I tried your snippet in this simple project [skeleton-starter-flow-chart-17.zip](https://github.com/vaadin/vaadin-charts/files/5429158/skeleton-starter-flow-chart-17.zip) and it looks like this.
![image](https://user-images.githubusercontent.com/9820084/96998592-60baad80-153c-11eb-8df6-c8ed9989a8e4.png)

Is it possible that you have setup a css theme for charts in your project? 
Something like `<dom-module id="chart" theme-for="vaadin-chart">` and defining values for `--vaadin-charts-color-0`, `--vaadin-charts-color-1`, etc? 
If you generated the project from start.vaadin.com before Vaadin 17 was released it could be part of `global-styles.js`.

There is more info about migrating to latest charts version depending on how you want to apply styles in [vaadin.com/docs](https://vaadin.com/docs/v17/charts/java-api/charts-migrating-from-earlier-versions.html)

**Comment by NicolasErnst** [comment]
Hello @alvarezguille, 

I created my project back then with Vaadin 14 and upgraded it to Vaadin 17 step by step. I found defined values for `--vaadin-charts-color-0`, etc. in a file called `shared-styles.js`. I am sorry I did not know that the Vaadin Starter Project already uses a custom css theme and defines these values by default.  Removing them solved the problem, thank you!
