### ISSUE TITLE
Vaadin charts flow 9.0.0 in Vaadin 14

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/vaadin-charts#557]
Hi,

I'm trying to use Vaadin charts flow 9.0.0 in a Vaadin 14.4.5 project.
If I'm using npm then the vaadin-chart web component is 7.0.0.
If I'm using pnpm then the vaadin-chart web component is 6.3.0.

I've noticed few things:
* package.json seems to be the same and contains: “@vaadin/vaadin-charts”: “7.0.0" (Good)
* package-lock.json contains:
"@vaadin/vaadin-charts": {
      "version": "7.0.0",
But also this:
    "@vaadin/vaadin-shrinkwrap": {
      "version": "14.4.5",
      ......
        "@vaadin/vaadin-charts": "^6.3.1",

* pnpm-lock.yaml contains:
*   '@vaadin/vaadin-charts': 6.3.1
and no 7.0.0.

Is there a solution for this?

Here is the screenshots.
<img width="1675" alt="vaadin14-charts-9_0_0" src="https://user-images.githubusercontent.com/51313578/104010711-9d9a5600-51b5-11eb-992c-e10bb583b58c.png">
<img width="1675" alt="vaadin14-charts_9_0_0_pnpm" src="https://user-images.githubusercontent.com/51313578/104010720-a12ddd00-51b5-11eb-963b-51b0ecb8daba.png">

And the 2 projects (npm and pnpm, only node_modules/target are removed). It's based on jetty but I have the same problem with spring-boot.

With npm:
[charts-9-v14-npm.zip](https://github.com/vaadin/vaadin-charts/files/5786900/charts-9-v14-npm.zip)
With pnpm:
[charts-9-v14-pnpm.zip](https://github.com/vaadin/vaadin-charts/files/5786901/charts-9-v14-pnpm.zip)

**Comment by tulioag** [comment]
This is not charts specific. Closing in favour of https://github.com/vaadin/flow/issues/9793.
