### ISSUE TITLE
Prepare Charts 8 for V14.x

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-charts#562]
- Prepare for PiT
- Write documentation for how to migrate to Charts 8 in V14.x
- Note limitations (no bower support)

**Comment by rolfsmeds** [comment]
As pnpm is default in V14.x, this is partially blocked by https://github.com/vaadin/flow/issues/9793

**Comment by Artur-** [comment]
> pnpm is default in V14.x,
That is not true, npm is the default

**Comment by rolfsmeds** [comment]
> > pnpm is default in V14.x,
> 
> That is not true, npm is the default

True that, disregard the blocking comment. I'll remove the label.
