### ISSUE TITLE
Marker in single point fillColor

### ISSUE THREAD

**Issue by juanfranciscolopez28** [vaadin/vaadin-charts#574]
Hi,
I have a problem with markers in single point LineChart.

This is the part of code with markers
```java
DataSeriesItem dataSeriesItem = new DataSeriesItem(time, value);
Marker marker = new Marker();
marker.setEnabled(true);
marker.setRadius(3);
if (!red) {
        marker.setFillColor(SolidColor.GREEN);
} else {
        marker.setFillColor(SolidColor.RED);
}
dataSeriesItem.setMarker(marker);
```
But point color not change
This is the result:
![imagen](https://user-images.githubusercontent.com/45214328/113599279-ab3d6b80-963e-11eb-8138-c576c7e15197.png)

This is the documentation of oficial highcharts about this:
https://api.highcharts.com/highcharts/series.line.data.marker.fillColor

And this is a fidle example working
https://jsfiddle.net/m46xyopu/

Thanks!!

**Comment by alvarezguille** [comment]
Thanks for reporting this @juanfranciscolopez28.
There's a bug with the serialization of the extra options when you only set a marker for the dataSeriesItem.
You can workaround this by setting the color to the item instead `dataSeriesItem.setColor(SolidColor.GREEN);`, you can still set the other options for the marker in this case and they will be serialized correctly, this has a side effect and it's that the color also applies to the border of the tooltip if it's enabled.
If you would like to avoid this side effect you can use `dataSeriesItem.setColor(null);` as the workaround and use `marker.setFillColor` as before to set the color of the point.

**Comment by alvarezguille** [comment]
Actually when I reproduced it locally I was doing `Marker marker = dataSeriesItem.getMarker();` and not `Marker marker = new Marker(); dataSeriesItem.setMarker(marker);`. In the first case I can reproduce the issue the workaround is needed, in the second case it works as expected. 
If you're in the second case using `dataSeriesItem.setMarker` it is possible that you're using both CSS and java styling for the chart, could you check if you are including `vaadin-chart-default-theme` somewhere in your project and also mention the Vaadin version?

**Comment by juanfranciscolopez28** [comment]
Hi,
Yes, i have styling in my charts.
```java
@CssImport(value = "./styles/chart.css", themeFor = "vaadin-chart", include = "vaadin-chart-default-theme")
@JsModule("@vaadin/vaadin-charts/theme/vaadin-chart-default-theme")
```
If i remove the two lines works. If i add @JsModule(with or without @CssImport) not work.

This examples are working
```java
       //@JsModule("@vaadin/vaadin-charts/theme/vaadin-chart-default-theme")
       Marker marker = dataSeriesItem.getMarker();
       marker.setFillColor(SolidColor.RED);
       dataSeriesItem.setColor(null);
```
```java
       //@JsModule("@vaadin/vaadin-charts/theme/vaadin-chart-default-theme")
       Marker marker = new Marker(true);
       marker.setFillColor(SolidColor.GREEN);
       dataSeriesItem.setMarker(marker);
       dataSeriesItem.setColor(null);
```
![imagen](https://user-images.githubusercontent.com/45214328/114014356-d1deea80-9868-11eb-83eb-1827ddc5a85b.png)


This is not working
```java
       @JsModule("@vaadin/vaadin-charts/theme/vaadin-chart-default-theme")
       Marker marker = dataSeriesItem.getMarker();
       marker.setFillColor(SolidColor.RED);
       dataSeriesItem.setColor(null);
```
![imagen](https://user-images.githubusercontent.com/45214328/114014240-b07dfe80-9868-11eb-84ed-f183b0cb015d.png)

I am using 19.0.2 vaadin.

Thanks!

**Comment by alvarezguille** [comment]
>Yes, i have styling in my charts.

Ok, that's the reason for the issue. 

Starting from Vaadin 18, Java API for theming is the default and you can switch to CSS styling, but if you switch to CSS then the styles coming from `vaadin-chart-default-theme` can override the the configuration done with Java which is what's happening here. 

As you can see when inspecting the color is coming from the default theme and not from the attribute:
![image](https://user-images.githubusercontent.com/9820084/114139835-33aa5d80-9918-11eb-901a-b8c0b93eb9bb.png)

We'll review documentation for this in case it's not clear enough.

The solution in this case is to keep all theme configuration either in css or in java.

To use CSS for your use case you can check for instance use `dataSeriesItem.setClassName(className);` or `dataSeriesItem.setColorIndex(colorIndex);` in your user case.

I don't know what configurations you have in `./styles/chart.css` so I can't make a suggestion on how to do that with Java.

**Comment by juanfranciscolopez28** [comment]
Hi!
I changed my code adding this and it works!
```java
dataSeriesItem.setColorIndex(1);
```
and css
```css
.highcharts-color-1 {
    fill: var(--lumo-success-color);
    stroke: var(--lumo-success-color);
}
```

Thank you for your help with this!!!

**Comment by alvarezguille** [comment]
Docs improved for V14 and latest branches.
