### ISSUE TITLE
Flags detach from flag-chart when changing the visible interval

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-charts#91]
<img width="692" alt="screen shot 2016-03-22 at 6 44 32 pm" src="https://cloud.githubusercontent.com/assets/883698/13973243/2739a582-f05e-11e5-9bd6-c21e682bd9e5.png">
To reproduce, go to http://demo.vaadin.com/vaadin-charts/ and change visible interval.

**Comment by alvarezguille** [comment]
This issue was fixed in [3.0.0-rc2](https://github.com/vaadin/vaadin-charts/releases/tag/3.0.0-rc2)
